// Lista completa de géneros de anime más comunes
export const ANIME_GENRES = [
  'Acción',
  'Aventura',
  'Carreras',
  'Ciencia Ficción',
  'Comedia',
  'Demencia',
  'Demonios',
  'Drama',
  'Ecchi',
  'Fantasía',
  'Harem',
  'Histórico',
  'Horror',
  'Josei',
  'Juegos',
  'Magia',
  'Artes Marciales',
  'Mecha',
  'Militar',
  'Misterio',
  'Música',
  'Parodia',
  'Policía',
  'Psicológico',
  'Romance',
  'Samurái',
  'Escolar',
  'Seinen',
  'Shoujo',
  'Shoujo Ai',
  'Shounen',
  'Shounen Ai',
  'Espacial',
  'Deportes',
  'Sobrenatural',
  'Súper Poderes',
  'Suspenso',
  'Terror',
  'Vampiros',
  'Yaoi',
  'Yuri'
].sort();
